apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-python-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/gleb-pp/iu-devops-course.git
    targetRevision: master
    path: k8s/mychart

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy: {}
