---
- name: Install Docker
  become: true
  tags:
    - docker
    - docker_install
  block:

    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: '0644'

    - name: Install Docker GPG key
      ansible.builtin.command: "gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg"
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable"
        state: present

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: true
      notify: Restart Docker

  rescue:

    - name: Wait before retrying Docker GPG key
      ansible.builtin.wait_for:
        timeout: 10

    - name: Retry apt update
      ansible.builtin.apt:
        update_cache: true

  always:

    - name: Ensure Docker service is enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true


- name: Configure Docker
  become: true
  tags:
    - docker
    - docker_config
  block:

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: true

    - name: Install python docker module
      ansible.builtin.apt:
        name: python3-docker
        state: present
